# Generated by Django 3.2.10 on 2022-05-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('user_password', models.CharField(max_length=50)),
                ('user_status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'users_tbl',
            },
        ),
    ]
